### ISSUE TITLE
drag and drop scroll ?

### ISSUE THREAD

**Issue by joeblew99** [web-padawan/brainy-table#1]
I am not sure what this really means....

is this for mobile ?

**Comment by web-padawan** [comment]
No, this is for desktop (and implemented using mouse events).
Check the [demo](http://kulikov.pp.ua/brainy-table/components/brainy-table/) and go to the `Scroll` tab, then move cursor over first demo - you'll see a `hand` cursor. Hold it and you'll be able to drag table to the left / right.

The possible use case is having native scroll hidden by default, which happens on Mac devices.

**Comment by joeblew99** [comment]
hey

thanks for explanation. I tried the demo and see what you mean.

I dont fully get the use case description, but seems like you have covered / fixed of an edge case i was not even aware of.

**Comment by web-padawan** [comment]
@joeblew99 see [this article](http://kb.tableau.com/articles/knowledgebase/displaying-scroll-bar) for better explanation.

**Comment by joeblew99** [comment]
ok thanks. will clsoe now.. appreciated
